### ISSUE TITLE
Any recommendation regarding "white-label" and "white-labelling"?

### ISSUE THREAD

**Issue by cristiklein** [inclusivenaming/website#138]
Is there any recommendation regarding [white-label product](https://en.wikipedia.org/wiki/White-label_product)? Tier 1, 2, 3 or no change?

**Comment by quaid** [comment]
> Is there any recommendation regarding [white-label product](https://en.wikipedia.org/wiki/White-label_product)? Tier 1, 2, 3 or no change?

Hi, thanks for this question, it's a good one considering the website doesn't reflect all of the work already done.

But because of the above, I can't easily find the entry that addresses this for "white box", which is a white-labeled computer. It's basically a no-change, with similar reasoning for "black box":  https://inclusivenaming.org/word-lists/no-change/#black-box

One thing we can do is make sure than an entry for "white box" includes "white-label(ing)" as the same thing, perhaps even in the title.

**Comment by cristiklein** [comment]
Thanks @quaid . I issued a PR to capture the recommendation.
